import streamlit as st
from groq import Groq
import os
from dotenv import load_dotenv

load_dotenv()

st.set_page_config(page_title="Kimi Chatbot AI", page_icon=":robot_face:", layout="centered")
st.title("Kimi Chatbot generated by Krishna Anand")
st.caption("A chatbot powered by Groq API")

client = Groq(api_key=os.getenv("GROQ_API_KEY")) 

if "messages" not in st.session_state:
    st.session_state["messages"] = []

for msg in st.session_state["messages"]:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

prompt = st.chat_input("Type your message here...")

if prompt:
    st.session_state["messages"].append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        placeholder = st.empty()
        full_response = ""

        stream = client.chat.completions.create(
            model="moonshotai/kimi-k2-instruct-0905",
            messages=st.session_state["messages"],
            max_tokens=2048,   # <-- FIXED
            temperature=0.7,
            stream=True
        )

        for chunk in stream:
            if chunk.choices and chunk.choices[0].delta and chunk.choices[0].delta.content:
                token = chunk.choices[0].delta.content
                full_response += token
                placeholder.markdown(full_response + "▌")

        placeholder.markdown(full_response)

        st.session_state["messages"].append(
            {"role": "assistant", "content": full_response}
        )
